package interpreter;

public enum Symbols {
    NEW, DELETE, MOVE, OFFSET, SCALE, LIST, ALL, GROUPS, GROUP, UNGROUP,
    AREA, PERIMETER, CIRCLE, RECTANGLE, IMG,
    OPEN_PARENTHESIS, CLOSE_PARENTHESIS, COMMA, QUOTE,
    POSITION, FLOAT, ID, PATH,
    EOF, INVALID
}
